// VIDEO
export const GET_VIDEO_ALL_REQ = "GET_VIDEO_ALL_REQ";
export const GET_VIDEO_ALL_SUCCESS = "GET_VIDEO_ALL_SUCCESS";
export const GET_VIDEO_ALL_FAILED = "GET_VIDEO_ALL_FAILED";
export const GET_VIDEO_DETAIL_REQ = "GET_VIDEO_DETAIL_REQ";
export const GET_VIDEO_DETAIL_SUCCESS = "GET_VIDEO_DETAIL_SUCCESS";
export const GET_VIDEO_DETAIL_FAILED = "GET_VIDEO_DETAIL_FAILED";

// FITUR UT CONNECT
export const GET_FITUR_UTCONNECT_REQ = "GET_FITUR_UTCONNECT_REQ";
export const GET_FITUR_UTCONNECT_FAILED = "GET_FITUR_UTCONNECT_FAILED";
export const GET_FITUR_UTCONNECT_SUCCESS = "GET_FITUR_UTCONNECT_SUCCESS";