export const MENU = {
    LANDING: '/Landing/',
    HOME: '/PartOnlineTransaction/',
    LIST_ORDER: '/PartOnlineTransaction/ListOrder',
    DETAIL_LIST_ORDER: '/PartOnlineTransaction/ListOrder/DetailListOrder',
    TRANSFER: '/PartOnlineTransaction/PaymentDetail',
    BUCKET_LIST: '/PartOnlineTransaction/Keranjang',
    PROMOTION: '/Landing/Promotion',
    DETAILPROMOTION: '/Landing/Promotion',
    DETAILVOUCHER: '/PartOnlineTransaction/Voucher',
    DELIVERY_METHODE: '/PartOnlineTransaction/ListOrder/DeliveryMethode',
    BILLING: '/BillingAddress',
    DETAIL_PROMOTION_LIST: '/Landing/ListNews/DetailNews',
    DETAIL_PRODUCT: '/PartOnlineTransaction/DetailProduct/',
    LIST_PRODUCT: '/PartOnlineTransaction/ListProduct',
    CHANGE_ADDRESS: '/ChangeAddress',
    LIST_NEWS: '/Landing/ListNews',
    USER_PROFILE: '/UserProfile',
    TERM_CONDITION: '/PartOnlineTransaction/TermCondition',
    WISHTLIST_PRODUCT: '/PartOnlineTransaction/WishtListProduct',
    LIST_VIDEO: '/Landing/ListVideo',
    DETAIL_VIDEO: '/Landing/ListVideo/DetailVideo',
}